name: Minecraft Server (Google Drive + Backup, Java 21, 7GB RAM)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */5 * * *"   # har 5 ghante restart

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 3600

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Java 21
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Install tools
      run: sudo apt-get install -y unzip zip curl

    - name: Setup rclone from base64 secret
      run: |
        mkdir -p ~/.config/rclone
        echo "${{ secrets.RCLONE_CONF_B64 }}" | base64 --decode > ~/.config/rclone/rclone.conf
        curl https://rclone.org/install.sh | sudo bash
        rclone version

    - name: Download server.jar
      run: |
        mkdir -p server
        rclone copy gdrive:/mc/server.jar server/

    - name: Download and extract world
      run: |
        if rclone ls gdrive:/mc/world.zip; then
          rclone copy gdrive:/mc/world.zip . --drive-acknowledge-abuse
          mkdir -p server/world
          unzip -o world.zip -d server/world
        else
          mkdir -p server/world
        fi

    - name: Download and extract plugins (safe)
      run: |
        mkdir -p server/plugins
        if rclone ls gdrive:/mc/plugins.zip; then
          rclone copy gdrive:/mc/plugins.zip . --drive-acknowledge-abuse || echo "Skipping plugins download due to abuse flag"
          if [ -f plugins.zip ]; then
            unzip -o plugins.zip -d server/plugins || echo "No plugins to extract"
          fi
        fi

    - name: Accept EULA
      run: echo "eula=true" > server/eula.txt

    - name: Set server.properties
      run: echo "online-mode=false" >> server/server.properties

    - name: Add server operator
      run: |
        echo '[{"uuid":"00000000-0000-0000-0000-000000000000","name":"NotDev42","level":4,"bypassesPlayerLimit":false}]' > server/ops.json

    - name: Start Minecraft server
      run: |
        cd server
        java -Xmx7G -Xms2G -jar server.jar nogui &
        sleep 60  # Large worlds ke liye safe start

    - name: Install Playit
      run: |
        curl -L https://github.com/playit-cloud/playit-agent/releases/latest/download/playit-linux-amd64 -o playit
        chmod +x playit
        ./playit --secret ${{ secrets.PLAYIT_SECRET }} &

    - name: Keep alive + auto backup every 30min
      run: |
        for i in {1..10}; do   # 10 * 30min = 5 hours
          sleep 1800
          cd server
          timestamp=$(date +%Y%m%d%H%M)
          zip -r world_$timestamp.zip world
          zip -r plugins_$timestamp.zip plugins
          rclone copy world_$timestamp.zip gdrive:/mc/ -P --drive-acknowledge-abuse
          rclone copy plugins_$timestamp.zip gdrive:/mc/ -P --drive-acknowledge-abuse
          cd ..
        done

    - name: Final backup world & plugins to Google Drive
      if: always()
      run: |
        cd server
        timestamp=$(date +%Y%m%d%H%M)
        zip -r world_$timestamp.zip world
        zip -r plugins_$timestamp.zip plugins
        rclone copy world_$timestamp.zip gdrive:/mc/ -P --drive-acknowledge-abuse
        rclone copy plugins_$timestamp.zip gdrive:/mc/ -P --drive-acknowledge-abuse
